# Generated by Django 4.1.5 on 2023-03-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_practicerecord_dental_practice_anesthesia_add_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicerecord",
            name="responsible_person",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, verbose_name="担当者"
            ),
        ),
    ]
