# Generated by Django 4.1.5 on 2023-03-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0006_practicerecord_responsible_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practicerecord",
            name="responsible_person",
        ),
        migrations.AddField(
            model_name="practicerecord",
            name="responsible_dhda",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="衛生士・助手",
            ),
        ),
        migrations.AddField(
            model_name="practicerecord",
            name="responsible_dr",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, verbose_name="歯科医師"
            ),
        ),
    ]
